.TH UPDATE-HUB 8 "January 2025" "update-hub-pkexec" "User commands"
.SH NAME
update-hub \- graphical update manager
.SH SYNOPSIS
.B update-hub-pkexec
.SH DESCRIPTION
.B update-hub-pkexec
runs update-hub as the super user/root (sudo)
.SH AUTHOR
Crypticverse <crypticversemc@gmail.com>
.SH SEE ALSO
.BR update-hub (1)
