.TH UPDATE-HUB 1 "January 2025" "update-hub" "User commands"
.SH NAME
update-hub \- graphical update manager
.SH SYNOPSIS
.B update-hub
.SH DESCRIPTION
.B update-hub
is a graphical application for managing system updates. It does not accept and command-line arguments and must
be launched from a terminal or application menu.
.SH AUTHOR
Crypticverse <crypticversemc@gmail.com>
.SH SEE ALSO
.BR apt (8)
